import { style } from "@vanilla-extract/css";
import { vars } from "../../../../shared/ui/styles/theme.css";

// 스타일 정의
export const apiAddStyles = {
  content: style({
    display: "flex",
    boxSizing: "border-box",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
    padding: "20px",
    width: "100%",
    height: "100%",
    background: vars.color.darkGrey,
    borderRadius: "8px",
    // Fixed Button 고려한 패딩 추가
    paddingBottom: "120px",
  }),
  row: style({
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  }),
  methodRow: style({
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  }),
  label: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.orange,
    textAlign: "left",
    marginRight: "10px",
    width: "100%",
  }),
  paramsLabel: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.green,
  }),
  bodyLabel: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.blue,
  }),
  responseLabel: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.purple,
  }),
  selectContainer: style({}),
  selectText: style({
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "13px",
    color: vars.color.white,
  }),
  endpointInput: style({}),
  section: style({
    display: "flex",
    flexDirection: "column",
    width: "100%",
    gap: "10px",
    border: `1px solid ${vars.color.darkGrey}`,
    borderRadius: "8px",
  }),
  sectionHeader: style({
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  }),
  bodyMetaContainer: style({
    display: "flex",
    gap: "16px",
    alignItems: "flex-end",
    width: "100%",
  }),
  bodyMetaItem: style({
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    flex: 1,
  }),
  bodyCheckboxContainer: style({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    width: "50px",
  }),
  bodyMetaDescription: style({
    flex: 2,
  }),
  labelSmall: style({
    fontFamily: "Pretendard",
    fontWeight: 500,
    fontSize: "12px",
    color: vars.color.white,
    textAlign: "left",
    height: "32px",
  }),
  bodyTypeContainer: style({}),
  spacer: style({
    height: "13px",
    width: "100%",
  }),
  buttonContainer: style({
    position: "absolute",
    left: "20px",
    bottom: "54px",
  }),
  paramItem: style({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    boxSizing: "border-box",
  }),
  explanationContainer: style({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "auto",
    minWidth: "80px",
    borderRadius: "4px",
    padding: "6px 0px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    flexShrink: 0,
    height: "32px",
    boxSizing: "border-box",
  }),
  inputField: style({
    flexGrow: 1,
    minWidth: "80px",
    background: vars.color.itemGrey,
    borderRadius: "4px",
    padding: "6px 8px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    boxSizing: "border-box",
    height: "32px",
    "::placeholder": {
      color: vars.color.inputPlaceholder,
    },
  }),
  inputFieldWide: style({
    flexGrow: 2,
    minWidth: "150px",
    background: vars.color.itemGrey,
    borderRadius: "4px",

    padding: "6px 8px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    boxSizing: "border-box",
    fontWeight: 400,
    fontSize: "13px",
    "::placeholder": {
      color: vars.color.inputPlaceholder,
    },
  }),
  inputFieldSmallDescription: style({
    display: "flex",
    alignItems: "center",
    flexGrow: 0.5,
    width: "100%",
    minWidth: "60px",

    borderRadius: "4px",
    border: `1px solid ${vars.color.darkGrey}`,
    padding: "6px 8px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    boxSizing: "border-box",
    height: "32px",
    "::placeholder": {
      color: vars.color.inputPlaceholder,
    },
  }),
  inputFieldSmallLabel: style({
    display: "flex",
    flexGrow: 0.5,
    width: "100%",
    minWidth: "60px",
    // background: vars.color.itemGrey,
    borderRadius: "4px",
    padding: "6px 0px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    boxSizing: "border-box",
    height: "32px",
  }),
  inputFieldSmall: style({
    display: "flex",
    flexGrow: 0.5,
    width: "100%",
    minWidth: "60px",
    background: vars.color.itemGrey,
    borderRadius: "4px",

    padding: "6px 8px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    boxSizing: "border-box",
    height: "32px",
    "::placeholder": {
      color: vars.color.inputPlaceholder,
    },
  }),
  paramTypeSelect: style({
    width: "80px",
    minWidth: "80px",
    background: vars.color.itemGrey,
    borderRadius: "4px",

    padding: "6px 10px",
    color: vars.color.white,
    fontFamily: "Pretendard",
    fontWeight: 400,
    fontSize: "13px",
    display: "flex",
    flexShrink: 0,
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",

    height: "32px",
    boxSizing: "border-box",
  }),
  paramText: style({
    fontSize: "13px",
    color: vars.color.white,
    whiteSpace: "nowrap",
  }),
  checkboxContainer: style({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "4px",
    minWidth: "50px",
    padding: "0 5px",
    height: "32px",
  }),
  checkboxLabel: style({
    fontSize: "13px",
    color: vars.color.white,
    cursor: "pointer",
    whiteSpace: "nowrap",
    paddingLeft: "4px",
  }),
  removeButton: style({
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    margin: 0,
    width: "24px",
    height: "24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  }),
  removeIcon: style({
    width: "16px",
    height: "16px",
    color: vars.color.white,
  }),
  paramItemHeader: style({
    display: "flex",
    alignItems: "center",
    gap: "8px",

    fontWeight: "bold",
    fontSize: "12px",
    color: vars.color.lightGrey2,
  }),
  removeButtonPlaceholder: style({
    width: "24px",
    height: "1px",
    flexShrink: 0,
  }),
  schemaPropertiesList: style({
    display: "flex",
    flexDirection: "column",
    width: "100%",
    paddingTop: "10px",
    rowGap: "10px",
  }),
  responseItemContainer: style({
    borderRadius: "6px",
    padding: "12px",
    backgroundColor: vars.color.itemGrey,
  }),
  responseHeader: style({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "12px",
  }),
  responseMetaInputGroup: style({
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
    flexGrow: 1,
  }),
  responseMetaItem: style({
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  }),
  responseMetaItemWide: style({
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    flexGrow: 1,
    minWidth: "200px",
  }),
  responseContentType: style({
    maxWidth: "250px",
  }),
  schemaPropertiesSection: style({
    paddingTop: "12px",
    borderTop: `1px dashed ${vars.color.darkGrey}`,
  }),
  schemaPropertiesHeader: style({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  }),
};
