import { vars } from "@/shared/ui/styles/theme.css";
import { style } from "@vanilla-extract/css";

export const metaDataStyles = {
  content: style({
    display: "flex",
    boxSizing: "border-box",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
    padding: "20px",
    width: "100%",
    height: "100%",
    background: vars.color.darkGrey,
    borderRadius: "8px",
  }),
  row: style({
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    width: "100%",
    padding: "0 20px",
  }),
  label: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.orange,
    textAlign: "left",
    width: "100%",
    marginRight: "10px",
    minWidth: "80px",
    marginBottom: "4px",
  }),
  tagLabel: style({
    fontFamily: "Pretendard",
    fontWeight: 600,
    fontSize: "14px",
    color: vars.color.orange,
    textAlign: "left",
    width: "100%",
    marginRight: "10px",
    minWidth: "80px",
    marginBottom: "15px",
  }),
  input: style({
    background: vars.color.itemGrey,
    borderRadius: "8px",
    padding: "8px 10px",
    color: vars.color.white,
    width: "100%",
    fontFamily: "Pretendard",
    fontSize: "13px",
    boxSizing: "border-box",
    height: "32px",

    "::placeholder": {
      color: vars.color.inputPlaceholder,
    },
  }),
  tagInputContainer: style({
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  }),
  tagList: style({
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "15px",
    width: "100%",
  }),
  tagItem: style({
    display: "inline-flex",
    alignItems: "center",
    backgroundColor: vars.color.darkBlue,
    padding: "8px",
    borderRadius: "6px",
    fontSize: "13px",
    color: vars.color.white,
    fontWeight: 500,
  }),
};
